<a href="https://colab.research.google.com/github/SamanMansoor/Data-Science/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Import the numpy package under the name np**

In [ ]:
import numpy as np

#**2. Print the numpy version and the configuration**

In [ ]:
print(np.__version__)
np.show_config

1.22.4


<function numpy.__config__.show()>

# **3. Create a null vector of size 10**

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# **4. How to find the memory size of any array**

In [4]:
a=np.zeros((10,10))
print("%d bytes" %(a.size*a.itemsize))

800 bytes


# **5. How to get the documentation of the numpy add function from the command line?**

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#**6. Create a null vector of size 10 but the fifth value which is 1**

In [7]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#**7. Create a vector with values ranging from 10 to 49**

In [9]:
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# **8. Reverse a vector (first element becomes last)**

In [12]:
z=np.arange(40)
z=z[::-1]
print(z)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#**9. Create a 3x3 matrix with values ranging from 0 to 8**

In [14]:
z=np.zeros(9).reshape(3,3)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# **10. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [16]:
n=np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4]),)


# **11. Create a 3x3 identity matrix**

In [17]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#**12. Create a 3x3x3 array with random values**

In [18]:
x=np.random.random((3,3,3))
print(x)

[[[0.35013365 0.03938654 0.48612395]
  [0.28135391 0.00779067 0.89811733]
  [0.26815332 0.29716848 0.15639479]]

 [[0.79533956 0.58219661 0.96880556]
  [0.66162508 0.15573228 0.57527855]
  [0.96531238 0.09348499 0.41907267]]

 [[0.65332821 0.5858287  0.07306688]
  [0.5999832  0.54625979 0.85384769]
  [0.2025286  0.00794497 0.23279968]]]


# **13. Create a 10x10 array with random values and find the minimum and maximum values**

In [19]:
z=np.random.random((10,10))
max,mix=z.max(),z.min()
print(max,min)

0.9856196542883667 <built-in function min>


#**14. Create a random vector of size 30 and find the mean value**

In [20]:
x=np.random.random(30)
m=x.mean()
print(m)

0.5210230648889966


#**15. Create a 2d array with 1 on the border and 0 inside**

In [22]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# **16. How to add a border (filled with 0's) around an existing array?**

In [23]:
x=np.ones((6,6))
z=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(z)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]



#**17. What is the result of the following expression?**

In [24]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

# **18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [25]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# **19. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [26]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# **20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [28]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#**21. Create a checkerboard 8x8 matrix using the tile function**

In [30]:
z-np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# **22. Normalize a 5x5 random matrix**

In [34]:
z=np.random.random((5,5))
z=(z-np.mean(z))/(np.std(z))
print(z)

[[ 0.9456471   1.00492785 -1.2694195  -0.77550936  1.59675416]
 [-1.38702806 -1.29664111  0.79557418  0.75722819  0.18424005]
 [-0.95885271  1.33823508 -0.83905708 -0.20116321  0.80601187]
 [ 0.22217815  0.46354533  1.23013601 -1.3181243  -1.37271216]
 [ 1.49290639 -0.88527717 -0.64958574  0.57912602 -0.46313997]]


# **23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)**

In [36]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


# ** 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [37]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# **25. Given a 1D array, negate all elements which are between 3 and 8, in place.**

In [38]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# **26. What is the output of the following script?**

In [39]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10
