<a href="https://colab.research.google.com/github/SamanMansoor/Data-Science/blob/main/Stress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
import warnings
import os

In [107]:
# Load the Excel file into a DataFrame
df = pd.read_excel('/content/Final (Data Analysis).xlsx')

# iterate through each column in the DataFrame
for col in df.columns:
    if df[col].dtype == 'object':
        # convert categorical data to numeric using pandas' factorize method
        df[col] = pd.factorize(df[col])[0]


print(df.head())

   Gender  Area (Living)  Age in years  Province  Weight (KG)    \
0       0              0            18         0           55.0   
1       0              0            18         0           55.0   
2       0              0            18         0           55.0   
3       1              0            18         0           55.0   
4       1              0            18         0           55.0   

   Height (Feet)  No. of siblings (Total number of sisters & Brothers)  \
0              0                                                  0      
1              0                                                  0      
2              0                                                  0      
3              1                                                  0      
4              1                                                  0      

   Your Highest Qualification  Family Occupation  Providing care to  ...  \
0                           0                  0                  0  ...   


In [108]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11401 entries, 0 to 11400
Columns: 134 entries, Gender to The program of study for my major was well integrated.
dtypes: float64(1), int64(133)
memory usage: 11.7 MB
None


In [109]:
print(df.describe())

             Gender  Area (Living)  Age in years      Province  Weight (KG)    \
count  11401.000000   11401.000000  11401.000000  11401.000000   11401.000000   
mean       0.501447       0.223489     22.317867      0.448031      60.801407   
std        0.672142       0.416602      6.936049      1.242644      13.959759   
min        0.000000       0.000000     10.000000      0.000000      16.000000   
25%        0.000000       0.000000     19.000000      0.000000      50.000000   
50%        0.000000       0.000000     20.000000      0.000000      60.000000   
75%        1.000000       0.000000     23.000000      0.000000      69.000000   
max       17.000000       1.000000     87.000000      6.000000     178.000000   

       Height (Feet)  No. of siblings (Total number of sisters & Brothers)  \
count   11401.000000                                       11401.000000      
mean       42.128498                                           3.916586      
std        18.470998                

In [110]:
print(df.shape)

(11401, 134)


In [111]:
df.isnull()

Gender  Area (Living)  Age in years  Province  Weight (KG)    \
0       False          False         False     False          False   
1       False          False         False     False          False   
2       False          False         False     False          False   
3       False          False         False     False          False   
4       False          False         False     False          False   
...       ...            ...           ...       ...            ...   
11396   False          False         False     False          False   
11397   False          False         False     False          False   
11398   False          False         False     False          False   
11399   False          False         False     False          False   
11400   False          False         False     False          False   

       Height (Feet)  No. of siblings (Total number of sisters & Brothers)  \
0              False                                              False      
1              False                                              False      
2              False                                              False      
3              False                                              False      
4              False                                              False      
...              ...                                                ...      
11396          False                                              False      
11397          False                                              False      
11398          False                                              False      
11399          False                                              False      
11400          False                                              False      

       Your Highest Qualification  Family Occupation  Providing care to  ...  \
0                           False              False              False  ...   
1                           False              False              False  ...   
2                           False              False              False  ...   
3                           False              False              False  ...   
4                           False              False              False  ...   
...                           ...                ...                ...  ...   
11396                       False              False              False  ...   
11397                       False              False              False  ...   
11398                       False              False              False  ...   
11399                       False              False              False  ...   
11400                       False              False              False  ...   

       The communication between teaching staff and students is good  \
0                                                  False               
1                                                  False               
2                                                  False               
3                                                  False               
4                                                  False               
...                                                  ...               
11396                                              False               
11397                                              False               
11398                                              False               
11399                                              False               
11400                                              False               

       I find teaching staff helpful when asked questions   \
0                                                  False     
1                                                  False     
2                                                  False     
3                                                  False     
4                                                  False     
...                

In [112]:
df.isnull().sum()

Gender                                                                                                                                            0
Area (Living)                                                                                                                                     0
Age in years                                                                                                                                      0
Province                                                                                                                                          0
Weight (KG)                                                                                                                                       0
                                                                                                                                                 ..
I frequently work together with others in my classes                                                            

In [113]:
df.dtypes

Gender                                                                                                                                              int64
Area (Living)                                                                                                                                       int64
Age in years                                                                                                                                        int64
Province                                                                                                                                            int64
Weight (KG)                                                                                                                                       float64
                                                                                                                                                   ...   
I frequently work together with others in my classes                        

In [114]:
# Calculate BMI
bmi = df['Weight (KG)  '] / ((df['Height (Feet)'] / 100) ** 2)

# Add BMI as a new column in the dataset
df['BMI'] = bmi


<ipython-input-114-8cbc4d30a54a>:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['BMI'] = bmi


In [115]:
df

Gender  Area (Living)  Age in years  Province  Weight (KG)    \
0           0              0            18         0           55.0   
1           0              0            18         0           55.0   
2           0              0            18         0           55.0   
3           1              0            18         0           55.0   
4           1              0            18         0           55.0   
...       ...            ...           ...       ...            ...   
11396       0              1            80         0          100.0   
11397       0              0            82         0           45.0   
11398       0              0            85         0           54.0   
11399       0              0            87         0           56.0   
11400       1              0            43         5           64.0   

       Height (Feet)  No. of siblings (Total number of sisters & Brothers)  \
0                  0                                                  0      
1                  0                                                  0      
2                  0                                                  0      
3                  1                                                  0      
4                  1                                                  0      
...              ...                                                ...      
11396             86                                                  6      
11397             86                                                  7      
11398             86                                                  7      
11399             86                                                  8      
11400             86                                                  6      

       Your Highest Qualification  Family Occupation  Providing care to  ...  \
0                               0                  0                  0  ...   
1                               1                  1                  1  ...   
2                               2                  1                  1  ...   
3                               1                  0                  2  ...   
4                               2                  2                  1  ...   
...                           ...                ...                ...  ...   
11396                           1                  0                  3  ...   
11397                           0                  0                  3  ...   
11398                           1                  0                  2  ...   
11399                           1                  2                  0  ...   
11400                           1                  2                  2  ...   

       I find teaching staff helpful when asked questions   \
0                                                      0     
1                                                      1     
2                                                      0     
3                                                      2     
4                                                      0     
...                                                  ...     
11396                                                  1     
11397                                                  3     
11398                                                  1     
11399                                                  0     
11400                                                  0     

       I manage to complete the requirements of the program without feeling unduly stressed  \
0                                                      0                                      
1                                                      0                                      
2                                                      0                                      
3                                                      1                                      
4                                   

In [116]:
df.isnull().any().any()  #This code tells you if you have some NaN value in you dataframe

False

In [117]:
df.isnull().any()

Gender                                                                                                                                            False
Area (Living)                                                                                                                                     False
Age in years                                                                                                                                      False
Province                                                                                                                                          False
Weight (KG)                                                                                                                                       False
                                                                                                                                                  ...  
I have frequently discussed ideas from courses with other students out-of-class         

In [118]:
import numpy as np
import pandas as pd

# Check for missing values
print(df.isnull().sum())

# Fill missing values with mean
df = df.fillna(df.mean())

# Check for infinite values
print(np.isinf(df).sum())

# Replace infinite values with NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Fill NaN values with mean
df.fillna(df.mean(), inplace=True)


Gender                                                                                                                                            0
Area (Living)                                                                                                                                     0
Age in years                                                                                                                                      0
Province                                                                                                                                          0
Weight (KG)                                                                                                                                       0
                                                                                                                                                 ..
I have frequently discussed ideas from courses with other students out-of-class                                 

In [131]:
from sklearn.model_selection import train_test_split

X = df.drop('Province', axis=1)
y = df.Province

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [132]:
print(np.isnan(y_train).any())
print(np.isinf(y_train).any())

False
False


In [133]:
X_train = X_train[~np.isnan(y_train) & ~np.isinf(y_train)]
y_train = y_train[~np.isnan(y_train) & ~np.isinf(y_train)]


In [134]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

# **LogisticRegression**

In [135]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(solver='liblinear')
lr_clf.fit(X_train, y_train)

print_score(lr_clf, X_train, y_train, X_test, y_test, train=True)
print_score(lr_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 85.73%
_______________________________________________
CLASSIFICATION REPORT:
                     0           1           2           3           4  \
precision     0.858903    0.416667    0.500000    0.500000    0.125000   
recall        0.998392    0.018248    0.008264    0.004065    0.003704   
f1-score      0.923410    0.034965    0.016260    0.008065    0.007194   
support    6841.000000  274.000000  121.000000  246.000000  270.000000   

                    5     6  accuracy    macro avg  weighted avg  
precision    0.750000   0.0  0.857268     0.450081      0.792785  
recall       0.018868   0.0  0.857268     0.150220      0.857268  
f1-score     0.036810   0.0  0.857268     0.146672      0.794282  
support    159.000000  69.0  0.857268  7980.000000   7980.000000  
_______________________________________________
Confusion Matrix: 
 [[6830    5    0    0    5    1    0]
 [ 267    5    1    0    1    0    0]
 [ 119    0    1    0    1    0    0]
 [ 2

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

In [136]:
test_score = accuracy_score(y_test, lr_clf.predict(X_test)) * 100
train_score = accuracy_score(y_train, lr_clf.predict(X_train)) * 100

results_df = pd.DataFrame(data=[["Logistic Regression", train_score, test_score]], 
                          columns=['Model', 'Training Accuracy %', 'Testing Accuracy %'])
results_df

Model  Training Accuracy %  Testing Accuracy %
0  Logistic Regression            85.726817           85.472084

In [137]:
from sklearn.tree import DecisionTreeClassifier


tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, y_train)

print_score(tree_clf, X_train, y_train, X_test, y_test, train=True)
print_score(tree_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                0      1      2      3      4      5     6  accuracy  \
precision     1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0   
recall        1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0   
f1-score      1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0   
support    6841.0  274.0  121.0  246.0  270.0  159.0  69.0       1.0   

           macro avg  weighted avg  
precision        1.0           1.0  
recall           1.0           1.0  
f1-score         1.0           1.0  
support       7980.0        7980.0  
_______________________________________________
Confusion Matrix: 
 [[6841    0    0    0    0    0    0]
 [   0  274    0    0    0    0    0]
 [   0    0  121    0    0    0    0]
 [   0    0    0  246    0    0    0]
 [   0    0    0    0  270    0    0]
 [   0    0    0    0    0  159    0]
 [   0    0    0    0    0    0   69]]

Test Resu

In [138]:
test_score = accuracy_score(y_test, tree_clf.predict(X_test)) * 100
train_score = accuracy_score(y_train, tree_clf.predict(X_train)) * 100

results_df_2 = pd.DataFrame(data=[["Decision Tree Classifier", train_score, test_score]], 
                          columns=['Model', 'Training Accuracy %', 'Testing Accuracy %'])
results_df = results_df.append(results_df_2, ignore_index=True)
results_df

<ipython-input-138-5ff1d90d217a>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append(results_df_2, ignore_index=True)


Model  Training Accuracy %  Testing Accuracy %
0       Logistic Regression            85.726817           85.472084
1  Decision Tree Classifier           100.000000           73.194972

In [139]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf_clf = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_clf.fit(X_train, y_train)

print_score(rf_clf, X_train, y_train, X_test, y_test, train=True)
print_score(rf_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                0      1      2      3      4      5     6  accuracy  \
precision     1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0   
recall        1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0   
f1-score      1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0   
support    6841.0  274.0  121.0  246.0  270.0  159.0  69.0       1.0   

           macro avg  weighted avg  
precision        1.0           1.0  
recall           1.0           1.0  
f1-score         1.0           1.0  
support       7980.0        7980.0  
_______________________________________________
Confusion Matrix: 
 [[6841    0    0    0    0    0    0]
 [   0  274    0    0    0    0    0]
 [   0    0  121    0    0    0    0]
 [   0    0    0  246    0    0    0]
 [   0    0    0    0  270    0    0]
 [   0    0    0    0    0  159    0]
 [   0    0    0    0    0    0   69]]

Test Resu

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [140]:
test_score = accuracy_score(y_test, rf_clf.predict(X_test)) * 100
train_score = accuracy_score(y_train, rf_clf.predict(X_train)) * 100

results_df_2 = pd.DataFrame(data=[["Random Forest Classifier", train_score, test_score]], 
                          columns=['Model', 'Training Accuracy %', 'Testing Accuracy %'])
results_df = results_df.append(results_df_2, ignore_index=True)
results_df

<ipython-input-140-9dfba9c0999c>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append(results_df_2, ignore_index=True)


Model  Training Accuracy %  Testing Accuracy %
0       Logistic Regression            85.726817           85.472084
1  Decision Tree Classifier           100.000000           73.194972
2  Random Forest Classifier           100.000000           85.764396